import { StyleSheet, Dimensions } from "react-native";
import { colors } from "../constants/Colors";

const { width } = Dimensions.get("window");

const styles = StyleSheet.create({
  contenedorGlobal: {
    flex: 1,
    backgroundColor: "#1a1a2e",
  },
  gradientBackground: {
    flex: 1,
  },
  contenedor: {
    flex: 1,
  },
  encabezado: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 15,
  },
  botonVolver: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    justifyContent: "center",
    alignItems: "center",
  },
  iconoVolver: {
    fontSize: 24,
    color: "#fff",
  },
  titulo: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#fff",
  },
  selectorPeriodo: {
    flexDirection: "row",
    marginHorizontal: 20,
    marginVertical: 15,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderRadius: 12,
    padding: 4,
  },
  botonPeriodo: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
  },
  botonPeriodoActivo: {
    overflow: "hidden",
  },
  gradientPeriodo: {
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: "center",
  },
  textoPeriodo: {
    color: "rgba(255, 255, 255, 0.6)",
    fontSize: 14,
    fontWeight: "600",
    textAlign: "center",
  },
  textoPeriodoActivo: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "bold",
  },
  seccionTarjetas: {
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  fila: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
    gap: 12,
  },
  tarjetaEstadistica: {
    flex: 1,
    aspectRatio: 1,
    borderRadius: 20,
    overflow: "hidden",
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  gradientTarjeta: {
    flex: 1,
    justifyContent: "center", 
    alignItems: "center", 
    padding: 16,
  },
  iconoTarjeta: {
    fontSize: 40, 
    marginBottom: 12, 
  },
  valorTarjeta: {
    fontSize: 32, 
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 4,
  },
  labelTarjeta: {
    fontSize: 13,
    color: "rgba(255, 255, 255, 0.95)",
    fontWeight: "600", 
    textAlign: "center",
  },
  seccion: {
    paddingHorizontal: 20,
    marginBottom: 25,
  },
  tituloSeccion: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 15,
  },
  tarjetaProgreso: {
    flexDirection: "row",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderRadius: 20, 
    padding: 24, 
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  infoProgreso: {
    flex: 1,
  },
  porcentajeGrande: {
    fontSize: 52,
    fontWeight: "bold",
    color: "#FF5252",
  },
  textoProgreso: {
    fontSize: 14,
    color: "rgba(255, 255, 255, 0.7)",
    marginTop: 5,
  },
  barraCircular: {
    justifyContent: "center",
    alignItems: "center",
  },
  circuloExterno: {
    width: 90, 
    height: 90,
    borderRadius: 45,
    padding: 5,
  },
  circuloGradient: {
    width: "100%",
    height: "100%",
    borderRadius: 45,
    justifyContent: "center",
    alignItems: "center",
  },
  circuloInterno: {
    width: 70, 
    height: 70,
    borderRadius: 35,
    backgroundColor: "#1a1a2e",
    justifyContent: "center",
    alignItems: "center",
  },
  textoCirculo: {
    fontSize: 18, 
    fontWeight: "bold",
    color: "#fff",
  },
  graficoContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderRadius: 20, 
    padding: 20,
    height: 220, 
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  barraContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-end",
  },
  barraWrapper: {
    width: "100%",
    height: 160, 
    justifyContent: "flex-end",
    alignItems: "center",
  },
  barra: {
    width: 32, 
    borderRadius: 10, 
    justifyContent: "flex-start",
    alignItems: "center",
    paddingTop: 6,
  },
  valorBarra: {
    fontSize: 11, 
    color: "#fff",
    fontWeight: "bold",
  },
  labelBarra: {
    fontSize: 12, 
    color: "rgba(255, 255, 255, 0.8)",
    marginTop: 10, 
    fontWeight: "600",
  },
  itemCategoria: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderRadius: 16, 
    padding: 16, 
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  infoCategoria: {
    flexDirection: "row",
    alignItems: "center",
    width: 110, 
  },
  puntoColor: {
    width: 14, 
    height: 14,
    borderRadius: 7,
    marginRight: 12, 
  },
  nombreCategoria: {
    fontSize: 15, 
    color: "#fff",
    fontWeight: "600",
  },
  barraCategoria: {
    flex: 1,
    height: 10, 
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 5,
    marginHorizontal: 15,
    overflow: "hidden",
  },
  rellenoCategoria: {
    height: "100%",
    borderRadius: 5,
  },
  cantidadCategoria: {
    fontSize: 15, 
    color: "#fff",
    fontWeight: "bold",
    width: 35,
    textAlign: "right",
  },
  itemHora: {
    marginBottom: 12,
  },
  tarjetaHora: {
    flexDirection: "row",
    alignItems: "center",
    padding: 18, 
    borderRadius: 16, 
    borderWidth: 1,
    borderColor: "rgba(255, 82, 82, 0.2)",
    elevation: 2,
    shadowColor: "#FF5252",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  rangoHora: {
    fontSize: 15, 
    color: "#fff",
    fontWeight: "bold",
    width: 70, 
  },
  barraHora: {
    flex: 1,
    height: 10, 
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 5,
    marginHorizontal: 15,
    overflow: "hidden",
  },
  rellenoHora: {
    height: "100%",
    borderRadius: 5,
  },
  porcentajeHora: {
    fontSize: 15, 
    color: "#FF5252",
    fontWeight: "bold",
    width: 50,
    textAlign: "right",
  },
});

export default styles;
