import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const estilos = StyleSheet.create({
  contenedorGlobal: {
    flex: 1,
    backgroundColor: '#1a1a2e',
  },
  gradientBackground: {
    flex: 1,
  },
  contenedor: {
    flex: 1,
  },
  encabezado: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 15,
  },
  botonVolver: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconoVolver: {
    fontSize: 24,
    color: '#fff',
  },
  titulo: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
  },
  selectorPeriodo: {
    flexDirection: 'row',
    marginHorizontal: 20,
    marginVertical: 15,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 12,
    padding: 4,
  },
  botonPeriodo: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
  },
  botonPeriodoActivo: {
    overflow: 'hidden',
  },
  gradientPeriodo: {
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: 'center',
  },
  textoPeriodo: {
    color: 'rgba(255, 255, 255, 0.6)',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  textoPeriodoActivo: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  seccionTarjetas: {
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  fila: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 15,
  },
  tarjetaEstadistica: {
    flex: 1,
    marginHorizontal: 5,
    borderRadius: 16,
    overflow: 'hidden',
  },
  gradientTarjeta: {
    padding: 20,
    alignItems: 'center',
  },
  iconoTarjeta: {
    fontSize: 32,
    marginBottom: 8,
  },
  valorTarjeta: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 4,
  },
  labelTarjeta: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.9)',
  },
  seccion: {
    paddingHorizontal: 20,
    marginBottom: 25,
  },
  tituloSeccion: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 15,
  },
  tarjetaProgreso: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 16,
    padding: 20,
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  infoProgreso: {
    flex: 1,
  },
  porcentajeGrande: {
    fontSize: 48,
    fontWeight: 'bold',
    color: '#FF5252',
  },
  textoProgreso: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.7)',
    marginTop: 5,
  },
  circuloExterno: {
    width: 80,
    height: 80,
    borderRadius: 40,
    padding: 4,
  },
  circuloGradient: {
    width: '100%',
    height: '100%',
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  circuloInterno: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#1a1a2e',
    justifyContent: 'center',
    alignItems: 'center',
  },
  textoCirculo: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#fff',
  },
  graficoContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 16,
    padding: 20,
    height: 200,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  barraContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  barraWrapper: {
    width: '100%',
    height: 140,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  barra: {
    width: 28,
    borderRadius: 8,
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingTop: 5,
  },
  valorBarra: {
    fontSize: 10,
    color: '#fff',
    fontWeight: 'bold',
  },
  labelBarra: {
    fontSize: 11,
    color: 'rgba(255, 255, 255, 0.7)',
    marginTop: 8,
  },
  itemCategoria: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 12,
    padding: 15,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  infoCategoria: {
    flexDirection: 'row',
    alignItems: 'center',
    width: 100,
  },
  puntoColor: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: 10,
  },
  nombreCategoria: {
    fontSize: 14,
    color: '#fff',
    fontWeight: '600',
  },
  barraCategoria: {
    flex: 1,
    height: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 4,
    marginHorizontal: 15,
    overflow: 'hidden',
  },
  rellenoCategoria: {
    height: '100%',
    borderRadius: 4,
  },
  cantidadCategoria: {
    fontSize: 14,
    color: '#fff',
    fontWeight: 'bold',
    width: 30,
    textAlign: 'right',
  },
  itemHora: {
    marginBottom: 12,
  },
  tarjetaHora: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 82, 82, 0.2)',
  },
  rangoHora: {
    fontSize: 14,
    color: '#fff',
    fontWeight: 'bold',
    width: 60,
  },
  barraHora: {
    flex: 1,
    height: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 4,
    marginHorizontal: 15,
    overflow: 'hidden',
  },
  rellenoHora: {
    height: '100%',
    borderRadius: 4,
  },
  porcentajeHora: {
    fontSize: 14,
    color: '#FF5252',
    fontWeight: 'bold',
    width: 45,
    textAlign: 'right',
  },
});